my:
  greeting: Hi - Update 4 for Bus Testing

app:
  developer:
    name: Sanchit Sharma

# Below is used in actuator
management.endpoints.web.exposure.include: "*"

#spring:
#  profiles:
#    active:
#    - test 
